apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: infra-crds
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./infrastructure/stacks/stacks/infra/crds/default
  prune: false
  dependsOn:
    - name: sources
  sourceRef:
    kind: GitRepository
    name: gitops
  force: true