apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: app1-db
  name: app1-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app1-db
  strategy: {}
  template:
    metadata:
      labels:
        app: app1-db
    spec:
      containers:
      - image: nginx
        name: nginx
        resources: {}
