apiVersion: apps/v1
kind: Deployment
metadata:
  name: podinfo-bis
spec:
  selector:
    matchLabels:
      app: podinfo
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9797"
      labels:
        app: podinfo
    spec:
      containers:
      - name: podinfod
        env:
        - name: ENV
          value: staging
