apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: podinfo
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./applications/podinfo/overlays/staging
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  validation: client
