apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: webapp
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/rayanebel/fluxv2-test
  ref:
    branch: master
  include:
    - repository:
        name: frontend
      fromPath: deploy/bases/frontend
      toPath: applications/stacks/base/frontend
    - repository:
        name: backend
      fromPath: deploy/bases/backend
      toPath: applications/stacks/base/backend
