---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: podinfo
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./applications/podinfo/base
  prune: false
  sourceRef:
    kind: GitRepository
    name: flux-system
  force: true