apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: app2
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./app2/overlays/staging
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  validation: client