name: release notes

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  release-notes:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}