on:
  pull_request:
    branches:
      - main


name: Test
jobs:
  print-env:
    name: Print ENV
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: |
          echo "REFERENCE: $GITHUB_HEAD_REF"
