name: alloydb:backup:kiln-devnet-sof-eth

on:
  workflow_dispatch:
  schedule:
    - cron: '*/15 * * * *'
    - cron: '*/30 * * * *'

permissions:
  id-token: write
  actions: write
  pull-requests: write
  issues: write
  contents: read

jobs:
  debug-ctx:
    runs-on: self-hosted
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

  cross-region-backup:
    timeout-minutes: 360
    runs-on: self-hosted
    if: github.event.schedule == '*/5 * * * *' || github.event_name == 'workflow_dispatch'
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: test
        run: |
          echo "test"
          sleep 10
          exit 1

      - name: 'notify:slack:failure'
        if: failure()
        uses: slackapi/slack-github-action@v1.26.0
        with:
          channel-id: C07JRDJ96AX
          payload: |
            {
              "text": "🚨 Cross-Region Snapshot: GitHub Action Build Result - ${{ job.status }}",
              "blocks": [
                {
                  "type": "header",
                  "text": {
                    "type": "plain_text",
                    "text": "🚨 Cross-Region AlloyDB Backup Failure",
                    "emoji": true
                  }
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "The cross-region backup process for AlloyDB has encountered an error and failed to complete."
                  }
                },
                {
                  "type": "divider"
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*Error Details:*\n- Backup creation did not succeed.\n- Please check the associated logs for more information."
                  }
                },
                {
                  "type": "divider"
                },
                {
                  "type": "actions",
                  "elements": [
                    {
                      "type": "button",
                      "text": {
                        "type": "plain_text",
                        "text": ":github: View Failed GitHub Action",
                        "emoji": true
                      },
                      "style": "danger",
                      "url": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
                    },
                    {
                      "type": "button",
                      "text": {
                        "type": "plain_text",
                        "text": ":gcp: View AlloyDB Cluster",
                        "emoji": true
                      },
                      "url": "https://console.cloud.google.com/alloydb/locations/europe-west1/clusters/kiln-devnet-sof-eth/overview?project=${{ vars.GOOGLE_DEVNET_PROJECT_ID }}"
                    }
                  ]
                }
              ]
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_NOTIFICATIONS_TOKEN }}
  
  monthly-backup:
    runs-on: self-hosted
    timeout-minutes: 360
    if: github.event.schedule == '*/8 * * * *'
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: test
        run: |
          echo "montlhy backup"
          sleep 60
          exit 0

      - name: 'notify:slack:failure'
        if: failure()
        uses: slackapi/slack-github-action@v1.26.0
        with:
          payload: |
            {
              "blocks": [
                {
                  "type": "header",
                  "text": {
                    "type": "plain_text",
                    "text": "🚨 Monthly AlloyDB Backup Failure",
                    "emoji": true
                  }
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "The monthly backup process for AlloyDB has encountered an error and failed to complete."
                  }
                },
                {
                  "type": "divider"
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*Error Details:*\n- Backup creation did not succeed.\n- Please check the associated logs for more information."
                  }
                },
                {
                  "type": "divider"
                },
                {
                  "type": "actions",
                  "elements": [
                    {
                      "type": "button",
                      "text": {
                        "type": "plain_text",
                        "text": ":github: View Failed GitHub Action",
                        "emoji": true
                      },
                      "style": "danger",
                      "url": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
                    },
                    {
                      "type": "button",
                      "text": {
                        "type": "plain_text",
                        "text": ":gcp: View AlloyDB Cluster",
                        "emoji": true
                      },
                      "url": "https://console.cloud.google.com/alloydb/locations/europe-west1/clusters/kiln-devnet-sof-eth/overview?project=${{ vars.GOOGLE_DEVNET_PROJECT_ID }}"
                    }
                  ]
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_NOTIFICATIONS_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
