on:
  pull_request:
    branches:
      - main


name: Test
jobs:
  print-env:
    name: Print ENV
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: script
        run: |
          set -x
          git fetch origin main
          chmod +x test.sh
          bash -x ./test.sh
        env:
          GITOPS_REFERENCE: ${{ env.GITHUB_HEAD_REF }}
