on:
  push:
    branches: [master]


name: Cache Example

jobs:
  cache-build:
    name: Build - With Cache
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: mkdir -p data && echo "Hello it's my data" > data/text.txt
      - uses: actions/cache@v2
        id: data
        with:
          path: ./data
          key: cache-data

  cache-use-build:
    name: Re-use Cache
    runs-on: ubuntu-latest
    needs: [cache-build]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - uses: actions/cache@v2
        id: data
        with:
          path: ./data
          key: cache-data
      - run: ls -la
      - run: ls -la data/
      - run: cat data/text.txt

  build-push:
    env:
        IMAGE: rayanebel/podinfo
    runs-on: ubuntu-latest
    steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
          username: rayanebel
          password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Docker tag prefix
      id: docker-tag
      run: | 
        export TAG="git-$(echo -n ${{ github.sha }} | head -c 7)"
        echo "::set-output name=tag-prefix::$TAG" 

    - name: Build and publish container image with tag
      uses: docker/build-push-action@v2
      with:
          push: true
          context: .
          file: ./dockerfiles/Dockerfile
          tags: |
            ${{ env.IMAGE }}:${{ steps.docker-tag.outputs.tag-prefix }}-${{ github.run_number }}

  # artifact-build:
  #   name: Build - With Artifact
  #   runs-on: ubuntu-latest

  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: actions/setup-node@v1
  #       with:
  #         node-version: 12
  #     - run: npm ci
  #     - run: npm run build
  #     - uses: actions/upload-artifact@v2
  #       with:
  #         name: nextjs-build
  #         path: ./.next

  # artifact-use-build:
  #   name: Re-use Artifact
  #   runs-on: ubuntu-latest
  #   needs: [artifact-build]

  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: actions/setup-node@v1
  #       with:
  #         node-version: 12
  #     - uses: actions/download-artifact@v2
  #       with:
  #         name: nextjs-build
  #     - run: ls .