on:
  workflow_dispatch:
  push:
    branches:
    - main

name: Test
jobs:
  test:
    name: 'test'
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v3
    - uses: Wandalen/wretry.action@master
      with:
        action: asdf-vm/actions/install@v2
        attempt_limit: 2
        attempt_delay: 2000
